$kind: http-example
request:
  url: https://api.getpostman.com/collections/:collectionId/roles
  method: PATCH
  pathVariables:
    collectionId: 12ece9e1-2abf-4edc-8e34-de66e74114d2
  body:
    type: json
    content: |-
      {
          "roles": [
              {
                  "op": "update",
                  "path": "/group",
                  "value": [
                      {
                          "id": 12345,
                          "role": "EDITOR"
                      },
                      {
                          "id": 123,
                          "role": "VIEWER"
                      }
                  ]
              },
              {
                  "op": "update",
                  "path": "/user",
                  "value": [
                      {
                          "id": 12345678,
                          "role": "EDITOR"
                      },
                      {
                          "id": 87654321,
                          "role": "VIEWER"
                      }
                  ]
              },
              {
                  "op": "update",
                  "path": "/team",
                  "value": [
                      {
                          "id": 123,
                          "role": "VIEWER"
                      },
                      {
                          "id": 543,
                          "role": "EDITOR"
                      }
                  ]
              }
          ]
      }
response:
  statusCode: 500
  statusText: Internal Server Error
  body:
    type: json
    content: |-
      {
          "type": "https://api.postman.com/problems/internal-server-error",
          "title": "Internal Server Error",
          "detail": "Internal Server Error",
          "status": 500
      }
    $type: |-
      {
          "type": "object",
          "properties": {
              "type": {
                  "type": "string",
                  "format": "uri",
                  "description": "The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem."
              },
              "title": {
                  "type": "string",
                  "description": "A short summary of the problem."
              },
              "detail": {
                  "type": "string",
                  "description": "Information about the error."
              },
              "status": {
                  "type": "integer",
                  "description": "The error's HTTP status code."
              }
          }
      }
order: 6000
