$kind: http-request
description: Adds workspace-environment associations to a system environment.
url: "{{baseUrl}}/api-catalog/system-environments/:systemEnvironmentId/associations"
method: POST
queryParams:
  - key: allowPartial
    value: ""
    disabled: true
    description: If false, the system only adds associations when there are no status errors. If true, the system skips any ineligible associations and adds eligible associations.
pathVariables:
  - key: systemEnvironmentId
    value: ""
    description: The system environment's ID.
body:
  type: json
  content: |-
    {
        "workspaceEnvironmentIds": [
            "{{workspaceEnvironmentId}}"
        ]
    }
examples: ./.resources/Add system environment associations.resources/examples
order: 6000
