$kind: http-request
description: |-
  Updates a system environment's information. You can update one or more fields in a single call.

  **Note:**

  If you update the name, it must be unique within the team.
url: "{{baseUrl}}/api-catalog/system-environments/:systemEnvironmentId"
method: PATCH
pathVariables:
  - key: systemEnvironmentId
    value: ""
    description: The system environment's ID.
body:
  type: json
  content: |-
    {
        "name": "{{systemEnvironmentName}}",
        "description": "{{systemEnvironmentDescription}}",
        "color": "{{systemEnvironmentColor}}",
        "isProduction": {{isSystemEnvironmentProduction}}
    }
examples: ./.resources/Update a system environment.resources/examples
order: 4000
