$kind: http-example
request:
  url: https://api.getpostman.com/monitors
  method: POST
  body:
    type: json
    content: |-
      {
          "monitor": {
              "name": "Test Monitor",
              "schedule": {
                  "cron": "0 0 * * *",
                  "timezone": "America/Chicago"
              },
              "collection": "12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2",
              "environment": "5daabc50-8451-43f6-922d-96b403b4f28e"
          }
      }
response:
  statusCode: 400
  statusText: Bad Request
  body:
    type: json
    content: |-
      {
          "error": {
              "name": "invalidUidError",
              "message": "The specified uid is invalid.",
              "details": {
                  "param": "environment",
                  "uid": "5daabc50-8451-43f6-922d-96b403b4f28e"
              }
          }
      }
    $type: |-
      {
          "type": "object",
          "properties": {
              "error": {
                  "type": "object",
                  "properties": {
                      "name": {
                          "type": "string",
                          "description": "The error name."
                      },
                      "message": {
                          "type": "string",
                          "description": "The error message."
                      },
                      "details": {
                          "type": "object",
                          "description": "Information about the error."
                      }
                  }
              }
          }
      }
order: 4000
