$kind: http-request
description: |-
  Updates the roles of users, groups, or teams in a collection. On success, this returns an HTTP `204 No Content` response.

  **Note:**

  - Only users assigned the `EDITOR` [role](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#collection-roles) in the collection can use this endpoint.
      
  - This endpoint does not support the external [Partner or Guest roles](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles).
url: "{{baseUrl}}/collections/:collectionId/roles"
method: PATCH
pathVariables:
  - key: collectionId
    value: ""
    description: The collection's ID.
    $type: |-
      {
        "type": "object",
        "properties": {
          "value": {
            "type": "string",
            "deprecated": false,
            "uniqueItems": false
          }
        },
        "required": [
          "value"
        ]
      }
body:
  type: json
  content: |-
    {
        "roles": [
            {
                "op": "update",
                "path": "{{pathValue}}",
                "value": [
                    {
                        "id": {{id}},
                        "role": "{{collectionRoleId}}"
                    }
                ]
            }
        ]
    }
  $type: |-
    {
        "type": "object",
        "required": ["roles"],
        "properties": {
            "roles": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["op", "path", "value"],
                    "properties": {
                        "op": {
                            "type": "string",
                            "description": "The operation to perform on the path.",
                            "enum": ["update"]
                        },
                        "path": {
                            "type": "string",
                            "description": "The resource to perform the action on.",
                            "enum": ["/user", "/group", "/team"]
                        },
                        "value": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "description": "Information about the updated role.",
                                "required": ["id", "role"],
                                "properties": {
                                    "id": {
                                        "type": "number",
                                        "description": "The user, group, or team's ID."
                                    },
                                    "role": {
                                        "type": "string",
                                        "description": "The role type:\n- `VIEWER` — Can view, fork, and export collections.\n- `EDITOR` — Can edit collections directly.",
                                        "enum": ["VIEWER", "EDITOR"]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
settings:
  disabledSystemHeaders: []
examples: ./.resources/Update a collection's roles.resources/examples
order: 2000
